-- CreateTable
CREATE TABLE "TrainingSection" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "note" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "courseId" INTEGER,
    "header1Flag" BOOLEAN NOT NULL DEFAULT true,
    "header1Name" TEXT,
    "header2Flag" BOOLEAN NOT NULL DEFAULT false,
    "header2Name" TEXT,
    "header3Flag" BOOLEAN NOT NULL DEFAULT false,
    "header3Name" TEXT,
    "header4Flag" BOOLEAN NOT NULL DEFAULT false,
    "header4Name" TEXT,
    "header5Flag" BOOLEAN NOT NULL DEFAULT false,
    "header5Name" TEXT,
    "selfEval1Flag" BOOLEAN NOT NULL DEFAULT false,
    "selfEval1Type" TEXT,
    "selfEval1Name" TEXT,
    "selfEval2Flag" BOOLEAN NOT NULL DEFAULT false,
    "selfEval2Type" TEXT,
    "selfEval2Name" TEXT,
    "adminEval1Flag" BOOLEAN NOT NULL DEFAULT false,
    "adminEval1Type" TEXT,
    "adminEval1Name" TEXT,
    "adminEval2Flag" BOOLEAN NOT NULL DEFAULT false,
    "adminEval2Type" TEXT,
    "adminEval2Name" TEXT,
    "adminEval3Flag" BOOLEAN NOT NULL DEFAULT false,
    "adminEval3Type" TEXT,
    "adminEval3Name" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "TrainingSection_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "TrainingCourse" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
