-- CreateTable
CREATE TABLE "TrainingMaterial" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "note" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "attachmentUrl" TEXT,
    "itemId" INTEGER,
    "detail1Flag" BOOLEAN NOT NULL DEFAULT true,
    "detail1Title" TEXT,
    "detail1Content" TEXT,
    "detail2Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail2Title" TEXT,
    "detail2Content" TEXT,
    "detail3Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail3Title" TEXT,
    "detail3Content" TEXT,
    "detail4Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail4Title" TEXT,
    "detail4Content" TEXT,
    "detail5Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail5Title" TEXT,
    "detail5Content" TEXT,
    "detail6Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail6Title" TEXT,
    "detail6Content" TEXT,
    "detail7Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail7Title" TEXT,
    "detail7Content" TEXT,
    "detail8Flag" BOOLEAN NOT NULL DEFAULT false,
    "detail8Title" TEXT,
    "detail8Content" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "TrainingMaterial_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "TrainingItem" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
